### ISSUE TITLE
Bug/Note: Standardise use of CAP vs GPA

### ISSUE THREAD

**Issue by jmestxr** [AY2223S2-CS2103T-T13-1/tp#104]
We should use CAP throughout in our documentation and app. There are currently some inconsistencies.

E.g. `view progress` command displays a success message that shows `Current GPA`, but the doughnut chart indicates `CAP`.
@Dangabit

**Comment by Dangabit** [comment]
I did indicate in the glossary DG that it is interchangeable. Anyway, I can change to follow the old format of CAP, but I not going to change the function name in the code (I stored them as GPA).
