### ISSUE TITLE
[PE-D][Tester C] App does not read from JSON immediately as its updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-1/tp#148]
After I input the delete all command, I edited the JSON file to add new modules. However the app does not read the updated JSON file. Changes are only reflected upon rebooting the app. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: glyfy/ped#3

**Comment by cjyothika** [comment]
Done in #179
