### ISSUE TITLE
[PE-D][Tester B] Incorrect Degree Progress

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-1/tp#158]
I have added the following mods:

![image.png](https://raw.githubusercontent.com/dillongoh/ped/main/files/7fd82542-20b3-4ab5-960d-e60162339974.png)

However, the degree progress is only 20/160:

![image.png](https://raw.githubusercontent.com/dillongoh/ped/main/files/6b95fbd3-f12f-4444-804f-d133fd92f851.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: dillongoh/ped#6

**Comment by Dangabit** [comment]
Update UG with a section to provide details on what these numbers and calculations are.

**Comment by cjyothika** [comment]
Done in #179
