### ISSUE TITLE
[PE-D][Tester A] Incorrect error message for edit commmand

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-1/tp#159]
I keyed in `edit cs2222 /M cs2223` and the software gives out the following error message:

![image.png](https://raw.githubusercontent.com/DerrickSaltFish/ped/main/files/742a22a4-62ab-4e3f-b5b8-9dd71bd45cfa.png)

However, it seems to me that the error is input wrong code prefix.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: DerrickSaltFish/ped#6

**Comment by cjyothika** [comment]
Fix check for presence of prefixes before checking module code validity. Similar fix for #147, #150.
