### ISSUE TITLE
[PE-D][Tester C] Error message slightly misleading

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-1/tp#162]
![image.png](https://raw.githubusercontent.com/glyfy/ped/main/files/478578b1-b11d-4438-988d-1777cb84ac35.png)
The issue here was I forgot to add the /m but instead it prompts that the module code is invalid. Maybe try and return a more appropriate error message?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: glyfy/ped#5

**Comment by Dangabit** [comment]
This one... Technically the error message is for find <module_code>, so not an issue. Although perhaps we can include "`help` for more info" or "`find` for formmatting guideline.
