### ISSUE TITLE
Delete modules

### ISSUE THREAD

**Issue by cjyothika** [AY2223S2-CS2103T-T13-1/tp#21]
As a user I can delete modules from my list, so that I can rectify a wrongly added module.

**Comment by Dangabit** [comment]
Idea: Implement by 
`delete all`: deletes all modules
`delete <module1>, <module2>, ...`: deletes multiple modules
`delete <module>`: delete specific modules

**Comment by Jun-How** [comment]
Oh maybe can use varags for this like this :D
https://www.baeldung.com/java-varargs

**Comment by jmestxr** [comment]
We can combine `delete /M` and `delete /m` to a single command `delete /m`, accepting one or more arguments

**Comment by Dangabit** [comment]
Yep I think reasonable to combine them.
