### ISSUE TITLE
Tag modules

### ISSUE THREAD

**Issue by cjyothika** [AY2223S2-CS2103T-T13-1/tp#25]
As a user, I can tag modules with different requirements(e.g. University Level Requirements, Computer Science Foundation etc) so that I can track which degree requirement each module fulfils.

**Comment by Dangabit** [comment]
Implementation Idea:
We have a persistent set of tags corresponding to the requirements of CS students.
`tag include <tag1>, <tag2>, ...`: Add multiple tags to this module.
`tag remove <tag1>, <tag2>, ...`: Remove tags from this module.

**Comment by jmestxr** [comment]
The tag name can be shortened:
University Level Requirements --> ULR
CS Foundation --> FDN
Industrial Experience --> IDE
CS Breadth & Depth --> B&D
Mathematics & Sciences --> SCI
Unrestricted Electives --> UE

**Comment by Dangabit** [comment]
I considered it when i made the models, I think it would be good to provide shortcuts but at the same time might be hard for new user to remember specific tags. For example, FDN for CS Foundation I was think CSF, different users might remember differently. Either we can accept both tags (short and long form) or we have some sort of autocomplete/list to show the accepted short-form tags.
