### ISSUE TITLE
How to determine which modules to include in the calculation of degree progress / summary?

### ISSUE THREAD

**Issue by jmestxr** [AY2223S2-CS2103T-T13-1/tp#46]
One suggestion is to only include modules that have grades keyed in. For those modules with no grades, we can assume that they are yet to be completed / planned by student to take in future semesters.

Can include this as a new user story.

**Comment by Dangabit** [comment]
I think that works, or we can also consider those modules tagged to show projected progression? Then the grades are like actual progression.

**Comment by jmestxr** [comment]
But then there will be modules that have tags but no grade.

I think we can categorise our modules into `completed` and `not completed / planning`.
`completed` modules are those modules with tags _and_ grade.
`not completed` modules are modules without tags or grade.

We can then have two degree progress, the `actual` progress that only takes `completed` modules into account, and the `projected` progress that takes both `completed` and `not completed` modules (i.e. all modules added by the user).

_Some suggestions on how this can be shown in the UI:_
- We can have two tabs in the GraphicsSection to toggle both degree progresses.

- In the ModuleList section of UI, we can differentiate `completed` and `not completed` modules something like: 
<img width="400" alt="Screenshot 2023-03-08 at 4 36 21 PM" src="https://user-images.githubusercontent.com/87931905/223663697-0a5977b5-24f0-444b-a7bc-072cb746c6ef.png">

On a small note, `Module` class can be updated to include the `isCompleted()` method.

**Comment by Dangabit** [comment]
I have implemented a `isComplete()` into module with the data update. Once it passes through, you can use it for the UI. I also have completedCredit and plannedCredit (completed + incomplete), perhaps in the degree progress you can include a bar to show the overall progress if possible? Pardon my poor drawing skills xd.

![image](https://user-images.githubusercontent.com/46040005/224619912-931fac26-c238-4155-9981-93e55795b7db.png)

**Comment by jmestxr** [comment]
Okay, this is a good idea. I'll work out the UI for this.

**Comment by Dangabit** [comment]
Completed with #58
