### ISSUE TITLE
Add new sort command

### ISSUE THREAD

**Issue by cjyothika** [AY2223S2-CS2103T-T13-1/tp#52]
As a user, I want to sort modules by subject (eg. CS, MA, GE), SemYear (done already), credits, level, tag, grade etc., to see how many of each type of module I have done.

**Comment by jmestxr** [comment]
Here is the suggested UI mockup for this implementation:

![Dashboard (1)](https://user-images.githubusercontent.com/87931905/223614697-2a984136-9386-46a2-ae2b-4a5a9bfc2301.png)

**Comment by jmestxr** [comment]
It can be `view modules /option`.

E.g. if I want to view modules sorted by grade, I'll enter `view modules /g`.
