### ISSUE TITLE
Prettify our error messages

### ISSUE THREAD

**Issue by jmestxr** [AY2223S2-CS2103T-T13-1/tp#65]
Currently, our error messages are a little hard to read, and not very user-friendly in my opinion. E.g.

<img width="415" alt="Screenshot 2023-03-11 at 11 34 51 PM" src="https://user-images.githubusercontent.com/87931905/224493415-372fa80b-8b73-43aa-8985-fb6ec4aa04ff.png">

Some suggestions I thought of:
- make each error message as straightforward as possible, and deal with empty / edge cases. E.g. for the case of delete, we just print a one liner: "Deleted module[s]: CS1010". Remove the part where "Could not find Module[s] to delete".

Perhaps this is partly because the width of the CliScreen of the GUI is a little too narrow. To overcome this, we could add newlines (`\n`) to segregate relevant subsections of the error message, like how we do it in code.

``` 
Invalid command format!

add: Adds a module to the module list.

Parameters: 
/m <MODULE CODE>
/c <MODULE CREDITS>
...

Example:
add /m CS1101S /y Y1S1 ...
```

**Comment by Jun-How** [comment]
In addition to re-formatting all error messages, I will be slightly modifying the correct output messages to make them look more user-friendly. This may include changes to certain classes.
