### ISSUE TITLE
Embed `sort` command into `view modules`?

### ISSUE THREAD

**Issue by jmestxr** [AY2223S2-CS2103T-T13-1/tp#66]
To further simplify things, instead of having an additional `sort` command, why don't we just add an extra parameter in `view modules` for the user to specify how they want their modules to be viewed? E.g. `view modules /c grade` where `c` represents `categorise`.

I feel that this could be a better design because the execution result of `sort` command is identical to `view modules` command, with `view modules` **sorting** modules by year/sem.

**Examples:**
`view modules` - displays list of modules sorted by year/sem (default behavior)
`view modules /c grade` or _simply_ `view modules /g` - displays list of modules sorted by grade
`view modules /c code` or _simply_ `view modules /m` - displays list of modules sorted by module code
etc

What do you guys think?

**Comment by Jun-How** [comment]
Hmm you make a good point, but I think typing out `view modules` again is kind of long and repetitive? As an alternative, maybe we can embed the sorting within the `list` command instead. In this case, `view modules` only needs to be called once to switch view, then the user can sort just by listing. I also think your second suggestion is better, which is just having the prefix to be sorted without the categorise. E.g. `list /g`, `list /m`

**Comment by jmestxr** [comment]
Oh right, I forgot we have a `list` command.

Should we instead change the syntax of `list` command to `view modules`? I think `view modules` is much clearer and more consistent with `view progress`.

**Comment by Dangabit** [comment]
Honestly, I don't like the `list` syntax also. I think we can allow switching of the screen between `view modules` and `view progress`. However, I think we should keep sort separate from view. Feels like it would be a hassle to type the whole thing out (like `view modules /by ...` every time we want to change the sorting.

**Comment by Dangabit** [comment]
Update: we will keep `sort` separate from `view modules`. Will also close this issue.
