### ISSUE TITLE
Specify our target audience and app constraints properly in UG

### ISSUE THREAD

**Issue by jmestxr** [AY2223S2-CS2103T-T13-1/tp#88]
According to [NUS Registrar Website](https://www.nus.edu.sg/registrar/academic-information-policies/modular-system), there exists the following edge cases for grades (refer to website for explanation on the grades):

**Exempted (EXE)**
_If I'm not wrong, EXE modules given advanced credit are added to the user's first semester of full-time CS undergraduate studies (will need to check this with NUS Registrar Office if not sure). If this is the case, the user can simply add these modules to the first semester (Y1S1) in our app._

**Incomplete (IC)**
_In our app, the user can simply delete the module he/she did not complete (for good reasons, hence given IC grade). Our app does not track IC modules._

**In Progress (IP)**
_In our app, the user will not be required to key in the IP grade, but rather can leave the grade field empty when module is added. Furthermore, for modules that go beyond a semester, the user only has to add (and can only add) the module once, either in the start semester or end semester (up to user's choice)_

**Withdrawn (W)**
_In our app, the user can simply delete the module he/she has withdrawn. Our app does not track withdrawn modules._

**Comment by Dangabit** [comment]
Yepp I think these are good ways to solve them. Perhaps we add them into the UG under adding of modules or QnA

The exempted ones can also put under Y0 (think we allowed that). But really up to the users...

**Comment by Dangabit** [comment]
New constraint: Our app currently doesn't support user retaking of a module.

**Comment by Jun-How** [comment]
To add on to withdrawn modules, modules which are are pass/fail (aka CS, CU grade) need to be taken into account too.

**Comment by Dangabit** [comment]
> To add on to withdrawn modules, modules which are are pass/fail (aka CS, CU grade) need to be taken into account too.

I was thinking to get the user use S and U for CS and CU too. There is no functional difference to them. However I discussed this with James before and since you brought it up too, yall think should separate? Or denote it somewhere in our UG?

**Comment by Jun-How** [comment]
> > To add on to withdrawn modules, modules which are are pass/fail (aka CS, CU grade) need to be taken into account too.
> 
> I was thinking to get the user use S and U for CS and CU too. There is no functional difference to them. However I discussed this with James before and since you brought it up too, yall think should separate? Or denote it somewhere in our UG?

I'm not sure if we can separate it in v1.4, but if possible I think would be better since they belong to different categories (might be a small nitpick for some users), but if not it's alright too since they function similar to an S/U grade, just that we need to state in the UG.

**Comment by Jun-How** [comment]
Compiled feedback from UG Consultation:
- Make command formats as accurate and elaborate as possible
- Use scenarios for commands (more user-friendly for target audience)
- Grammar fix
- Page break
- Longer intro, give overview
- Give alternatives in GUI (clicking)
- Look through all command formats to ensure accuracy (e.g. missing prefix?) (e.g. view, find, tag)
- SS with label descriptions below

**Comment by Dangabit** [comment]
Resolved in UG
