### ISSUE TITLE
Add missing user stories to UG

### ISSUE THREAD

**Issue by jmestxr** [AY2223S2-CS2103T-T13-1/tp#89]
The following user stories are to be added to the UG, based on v1.2 and v1.3 implementation:

**`sort` command:** see #52 
* As a user, I want to sort modules by subject (eg. CS, MA, GE), SemYear (done already), credits, level, tag, grade etc., to see how many of each type of module I have done.

**`view progress` command:** see #58 
* As an NUS CS student, I want to view my CAP, so that I can know how well I have done so far in my CS
* As an NUS CS student, I want to check how much of each degree requirement I have completed, so that I know what requirements I still need to complete.
* As an NUS CS student, I want to view my current degree completion progress in terms of percentage and number of MCs completed.

<br>

_**P.S.**_ Should we categorise our user stories by features/commands we implemented, instead of having it all in one table?

<img width="500" alt="Screenshot 2023-03-19 at 11 59 53 PM" src="https://user-images.githubusercontent.com/87931905/226188388-c076ac45-7a78-4433-8362-202150ed09f3.png">

**Comment by Dangabit** [comment]
What does level refer to for the sorting?

**Comment by Dangabit** [comment]
Also I think leaving it as one table is fine. I did some reordering so that it flows like our features list.
