### ISSUE TITLE
Documentation Bugs

### ISSUE THREAD

**Issue by Dangabit** [AY2223S2-CS2103T-T13-1/tp#99]
Please collate all the documentation bugs you find here!

Those that are done, please indicate with a 👍

**Comment by Dangabit** [comment]
Bug: index.md badges for CI and CodeCov shows AB3's ones.

Change codecov badge image source to "https://codecov.io/gh/AY2223S2-CS2103T-T13-1/tp/branch/master/graph/badge.svg"
and JavaCI to "https://github.com/AY2223S2-CS2103T-T13-1/tp/workflows/Java%20CI/badge.svg"

**Comment by jmestxr** [comment]
Under DG `implementation section` for sort command, the activity diagram is a little too small.

**Comment by jmestxr** [comment]
Under DG `implementation section`, the following diagrams _which I feel are important_ are missing:
- ui <---> logic sequence diagram for find command 
- logic sequence diagram for view command

<---> denotes interaction

If we are up to it, we could also, for each implementation, add sequence diagrams that show high-level interactions between ui + logic + model.

**Comment by Dangabit** [comment]
Check through all documents and remove any resemblances of AB3. We can split the work for this.

**Comment by Dangabit** [comment]
Update any GUI screenshots of our app, for UG, DG (?), README ...

**Comment by Jun-How** [comment]
Update JavaDocs, probably need to split the work for this too.

**Comment by jmestxr** [comment]
**DG: to update Use Cases.**

For example, there is missing information such as in:
<img width="565" alt="Screenshot 2023-04-02 at 11 17 16 PM" src="https://user-images.githubusercontent.com/87931905/229362236-ffd32667-8dd0-4ca5-8981-5d917aa0a90f.png">
Should be: The given module code, credits or year-semester is missing or invalid.

**Comment by jmestxr** [comment]
> **DG: to update Use Cases.**
> 
> For example, there is missing information such as in: <img alt="Screenshot 2023-04-02 at 11 17 16 PM" width="565" src="https://user-images.githubusercontent.com/87931905/229362236-ffd32667-8dd0-4ca5-8981-5d917aa0a90f.png"> Should be: The given module code, credits or year-semester is missing or invalid.

Resolved

**Comment by jmestxr** [comment]
> Update any GUI screenshots of our app, for UG, DG (?), README ...

Resolved
